# Generated by Django 6.0.3 on 2026-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField()),
                ('image', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('description', models.CharField(verbose_name=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.CharField()),
                ('link', models.CharField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
